### ISSUE TITLE
Sorry for creating this issue

### ISSUE THREAD

**Issue by ppamorim** [Mojang/web-theme-bootstrap#5]
Hi, I am really sorry by creating this non relational issue on your repository. But things are getting out of control. I tried to reach contact with your but I got no answer, even on critical situations like mine.

My account was hacked this Saturday (4/8/2018) and I restored it hours later. I noticed that the hacker also changed my name and I can't change it in 30 days. I send a message to your support team and they don't answered yet me and the expected time will be in 12 DAYS, which is not acceptable. I am unable to play with my friends during this time since all my setup is done on my old account and the server doesn't accept different nicknames.

Please fix it soon as possible. Contact me for more information.

**Comment by mariakatsourani** [comment]
Please contact [https://help.mojang.com/](https://help.mojang.com/)
